### ISSUE TITLE
Two-way binding

### ISSUE THREAD

**Issue by knchess** [geoffreybauduin/ion-range-slider-angularjs#4]
I think it would be nice if the directive updated scope.from and scope.to when the slider's internal model changes.

Something like this:

`onChange: function (a) {
    $scope.from = a.from;
    $scope.to = a.to;
    $scope.onChange && $scope.onChange({
        a: a
    });
},`

**Comment by geoffreybauduin** [comment]
It has been done in #6 as far as I know.
